apiVersion: v1
entries:
  tapopa-messenger:
  - annotations:
      artifacthub.io/license: AGPL-3.0-or-later
    apiVersion: v2
    appVersion: 0.1.0
    created: "2026-01-15T15:58:50.091404128Z"
    description: Messenger by Tapopa.
    digest: e99b29e2461e64cef0c07ea0e764aaf7405de3cd73989aa422f5bdb70e23b07f
    name: tapopa-messenger
    sources:
    - https://github.com/tapopa/messenger
    type: application
    urls:
    - https://tapopa.github.io/messenger/helm/tapopa-messenger-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-15T15:58:50.090564813Z"
